### ISSUE TITLE
Integrate to GlassFish

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish-grizzly#2027] opened 2018-11-09 16:24 UTC
- [x] Integrate to Eclipse GlassFish
- [x] Pass all CTS/TCK tests

#2025 must be finished before starting working on this task.

**Comment by anajosep** [comment] 2018-12-03 14:31
Submitted this PR to integrate Eclipse Grizzly 2.4.4 and Eclipse Grizzly NPN 1.9 to Eclipse GlassFish
https://github.com/eclipse-ee4j/glassfish/pull/22650

**Comment by anajosep** [comment] 2018-12-08 05:55
The PR is merged. The CTS/TCK certification is pending.

**Comment by anajosep** [comment] 2018-12-10 11:40
If there are any new/additional CTS test failures whose root cause if suspected to be caused by the new version of Grizzly, I would be filing a separate tracking bug for the same. Closing this issue.

**Closed as completed by anajosep** 2018-12-10 11:40 UTC
Labels: GlassFish 5.1
